version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
